services:
  dotnet-app:
    build:
      context: ./hotel-backend
      dockerfile: Dockerfile
    ports:
      - "7151:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
  react-app:
    build:
      context: ./hotel-frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
