@hotel_backend_HostAddress = https://localhost:7251

GET {{hotel_backend_HostAddress}}/hotels
Accept: application/json

###

@id=1
GET {{hotel_backend_HostAddress}}/hotels/{{id}}
Accept: application/json

###